AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template is a stack to create GoldenAMI by SSM-Automation.

Parameters:
  ProjectName:
    Type: String
  RoleName:
    Type: String
  Environment:
    Type: String
  OperatorEMail:
    Description: EMail address to notify if there are any scaling operations
    Type: String
    AllowedPattern: >-
      ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: must be a valid email address.

Resources:

  CodeCommitNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${ProjectName}-${RoleName}-${Environment}-codecommit-sfn-topic
      TopicName: !Sub ${ProjectName}-${RoleName}-${Environment}-codecommit-sfn-topic
      Subscription:
        - Endpoint: !Ref OperatorEMail
          Protocol: email

  # -----------------------------------------
  # CodeCommit Repository
  # -----------------------------------------
  CodeCommitSfnPipelineRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-${RoleName}-bluegreen-sfn-pipeline
      RepositoryDescription: CodeCommit Repository
      Triggers:
        - Name: MasterTrigger
          CustomData: !Ref AWS::StackName
          DestinationArn: !Ref CodeCommitNotificationTopic
          Events:
            - all

Outputs:
  CodeCommitSfnRepoARN:
    Description: CodeCommit Repository ARN
    Value: !GetAtt CodeCommitSfnPipelineRepo.Arn
    Export:
      Name: !Sub ${ProjectName}-${RoleName}-bluegreen-sfn-pipeline-repo-arn

  CodeCommitSfnRepoName:
    Description: CodeCommit Repository NAME
    Value: !GetAtt CodeCommitSfnPipelineRepo.Name
    Export:
      Name: !Sub ${ProjectName}-${RoleName}-bluegreen-sfn-pipeline-repo-name
